#!/bin/sh
echo "We are installing OpenLinux version 1.17 onto your system. Please wait.";
echo "We are attempting to run sudo commands... Please enter your password if you get prompted.";
sudo ./reporter/worked.sh;
echo ""
